### ISSUE TITLE
Can't access transform() without calling data().

### ISSUE THREAD

**Issue by hastebrot** [vega/vega-lite-api#14]
I have to write `spec = vl.data().transform(...transforms)` (forced to call `data()` before `transform()`) in order to use it with `react-vega-lite` as `<VegaLite spec={spec} data={data} />`.

**Comment by jheer** [comment]
Yes, the `transform` method is not defined in the top level scope. The current design requires that you either create a specific mark context or use the `data` method, which can convert to a mark context once a mark method or composition operator (layer, hconcat, etc) is invoked. We need to have `data` as a top-level method in order to also support data set references for the `lookup` transform.

It could be possible to add a top-level `transform` method that acts similarly to data (it can convert to a mark context), but only if strictly necessary. I don't want to inflate the API surface area unless we really need to!

**Comment by jheer** [comment]
Closing the issue for now, as there are currently no plans to expand the API surface area to include transform at the top-level. Instead, one should call `data` or a specific `mark` or composition operator method first.
