### ISSUE TITLE
use the same syntax as altair ?

### ISSUE THREAD

**Issue by djouallah** [vega/vega-lite-api#2]
sorry, just a business users here with non programming background,  just a thought is there a technical reason not to use the same syntax as python  altair, it is very friendly and easy to code.

**Comment by jheer** [comment]
The syntax is already similar to Altair, both by design and due to the fact that both use Vega-Lite. However, some discrepancies are going to naturally occur due to the differences between JavaScript and Python: both in terms of language features (JavaScript lacks support for keyword arguments) and common conventions. If there is a specific design aspect you think could be made more user-friendly, please open a new issue with a description and examples of how you think the syntax should look!
