### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by RandomFractals** [vega/vega-lite-api#7]
Introduction of this new vega-lite api is a bit confusing to me since we've explored this subject in deapth in other places.

Will it also include C# & java interfaces per my quick recon on that here: 

https://github.com/RandomFractals/vega-lite-api

|| you are just rolling out your own again?

& what happened to us backing up Vizsla?

https://github.com/gjmcn/vizsla

Did you guys reach out to @gjmcn before you closed that long thread we had and created this new vega-lite js api repo?

Hmm... 🤔

**Comment by jheer** [comment]
Sorry, I'm not sure what thread you are referring to, and I did not close it.

I built this API in order to have a full-featured API for Vega-Lite that I can use in the visualization course I'm currently teaching. It is intended to provide parity with Altair, allowing students to choose to use either Python or JavaScript, depending on their background and interests.

You can see the resulting curriculum of notebooks here:
https://github.com/uwdata/visualization-curriculum

I have not yet reached out to @gjmcn (hi Graham!) but I intended to once the mad rush here settled down a bit (development has proceeded in a rather hurried fashion, given time constraints). Vizsla is wonderful, but this project takes a different approach to API generation and I needed a more full-featured API for our educational curriculum.

Future plans beyond the JS API here are still up in the air, but I do think the high-level API design approach we're exploring in this project could be used to generate APIs for other languages in the future. Thanks for sharing the link to your API repo; I had not seen that yet and will take a look at it at a later date.

**Comment by RandomFractals** [comment]
@jheer ok. that explains. thanks for this followup. 

@kanitw can you link us to that long thread you closed last month? for full scope & introspection? I am not sure if it was in vega-lite repo originally or vega.

I look forward to watching what you guys do with this api and please collabe with @gjimcn on it too. 

Add support for other languages like C# & Java would be nice too as part of this effort.

**Comment by kanitw** [comment]
Hi

Im not sure which thread you mean?

**Comment by RandomFractals** [comment]
hah! ok. I found it: https://github.com/vega/vega-lite/issues/2280

**Comment by RandomFractals** [comment]
@jheer I took a quick look at js notebook you've created for this library and your visualization course curriculum. I really liked your intro and had to share it with the twitter-verse since I have a lot of posts there tagged with vegaViz: https://twitter.com/TarasNovak/status/1118490993320497152

Feel free to close this issue and thank you for the background history on this library creation & ideation process.

**Comment by jheer** [comment]
Glad you like it but please do NOT publicly announce at this time. The curriculum is under development and we are planning an announcement later on once it is complete and has been trial run through my current course.

**Comment by RandomFractals** [comment]
sorry, too late. I already blasted it. I don't have many followers so I doubt anyone would notice those tweets.

**Comment by jheer** [comment]
Ok, thanks!
